<?php
require_once dirname(__DIR__) . '/_includes/bootstrap.php';

PageTitle("Talks");
PageSubtitle("Working-group talks and presentations");
PageStart("talks/");

/**
 * talks_table: date, title, url, presenter, event
 * Optional extra files: more => [ ['text' => '…', 'url' => '…'] ]
 */

talks_table('Talks & Presentations', [
    [
        'date' => '03-2023',
        'title' => 'Møller Polarimetry High-Precision Systematic Studies',
        'url' => 'talks/docs/3-15-Moller-Meas--HallA-Weekly-Meeting--Final.pdf',
        'presenter' => 'Eric King',
        'event' => 'Hall-A Weekly Meeting',
    ],
    [
        'date' => '01-2023',
        'title' => 'Review of Møller NIM-A Publications and MOLLER Preparations',
        'url' => 'talks/docs/2023-Winter-HallA-Collaboration-Meeting.pdf',
        'presenter' => 'Eric King',
        'event' => '2023 Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '10-2022',
        'title' => 'High-precision Møller Polarimetry at Jefferson Lab’s Hall A',
        'url' => 'talks/docs/PSTP22_High_Precision_Moller_Polarimetry_Eric_King_final.pdf',
        'presenter' => 'Eric King',
        'event' => 'Mainz PTSP \'22',
    ],
    [
        'date' => '06-2022',
        'title' => 'Møller Polarimetry for MOLLER',
        'url' => 'talks/docs/MOLLER-June-2022-Collab-Moller-Polarimeter.pdf',
        'presenter' => 'Eric King',
        'event' => 'MOLLER Collaboration Meeting',
    ],
    [
        'date' => '02-2022',
        'title' => 'Future Hall-A Polarimetry',
        'url' => 'talks/docs/polarimetry_halla_future_gaskell.pdf',
        'presenter' => 'Dave Gaskell',
        'event' => '2022 Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '02-2022',
        'title' => 'CREX Polarimetry',
        'url' => 'talks/docs/CREX-Polarimetry-2022-HallA-Winter-Mtg.pdf',
        'presenter' => 'Eric King',
        'event' => '2022 Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '12-2021',
        'title' => 'Moller Polarimetry Update',
        'url' => 'talks/docs/MollerCollabDec2021-DCJones.pdf',
        'presenter' => 'Don Jones',
        'event' => 'MOLLER Collaboration Meeting :: December 2021',
    ],
    [
        'date' => '10-2021',
        'title' => 'Challenges to Reaching 0.4% Møller Polarimetry in Hall-A at Jefferson Lab.',
        'url' => 'talks/xxxxFILExxxx',
        'presenter' => 'Eric King',
        'event' => 'Fall 2021 Meeting of the Division of Nuclear Physics of the American Physical Society.',
    ],
    [
        'date' => '04-2021',
        'title' => 'High-Precision Møller Polarimetry in Hall A at Jefferson Lab During the 12GeV Era.',
        'url' => 'talks/docs/APS_April_2021_Quarks_to_Cosmos_Moller_Polarimetry_Eric_King_Jr.pdf',
        'presenter' => 'Eric King',
        'event' => 'Sping 2021 American Physical Society Conference',
    ],
    [
        'date' => '01-2021',
        'title' => 'Møller Polarimetry in Hall-A Jefferson Lab.',
        'url' => 'talks/docs/JLab_HA_Jan2021.pdf',
        'presenter' => 'Eric King',
        'event' => '2021 Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '10-2020',
        'title' => 'Key Møller Polarimetry Systematics for the PREX-II/CREX Experiments.',
        'url' => 'talks/xxxxFILExxxx',
        'presenter' => 'Eric King',
        'event' => 'Fall 2020 Meeting of the Division of Nuclear Physics of the American Physical Society',
    ],
    [
        'date' => '10-2019',
        'title' => 'Møller Polarimetery Simulation for Jefferson Lab Hall-A',
        'url' => 'talks/docs/2019_PTSP__JLab_Hall-A_Moller_Polarimetry_MolPol.pdf',
        'presenter' => 'Eric King',
        'event' => 'PSTP 2019',
    ],
    [
        'date' => '03-2018',
        'title' => 'Møller Polarimeter DAQ System Overview',
        'url' => 'talks/docs/Moller-DAQs.pdf',
        'presenter' => 'Roman Pomatsalyuk',
        'event' => 'Møller Polarimetry Working Group Meeting',
    ],
    [
        'date' => '03-2017',
        'title' => 'Møller Polarimeter for PREX2/CREX',
        'url' => 'talks/docs/Prex_Moller_polarimeter.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'PREX2 Collaboration Meeting',
    ],
    [
        'date' => '05-2016',
        'title' => 'Results of the Møller Polarimeter Studies',
        'url' => 'talks/docs/weekly_05.10.2016.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Weekly Meeting',
    ],
    [
        'date' => '04-2016',
        'title' => 'Status of the Hall A Møller Polarimeter',
        'url' => 'talks/docs/Sasha-Moller-MOLLER.2016.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'MOLLER Collaboration Meeting',
    ],
    [
        'date' => '02-2016',
        'title' => 'Status of the Hall A Møller Polarimeter',
        'url' => 'talks/docs/Sasha-Moller_for_PREX.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'PREX/CREX Collaboration Meeting',
    ],
    [
        'date' => '01-2016',
        'title' => 'Møller Polarimeter Test at 11GeV',
        'url' => 'talks/docs/weekly_2016_01_05.pdf',
        'presenter' => 'Roman Pomatsalyuk',
        'event' => 'Møller Polarimetry Working Group Meeting',
    ],
    [
        'date' => '01-2015',
        'title' => 'Super-conducting Solenoid Field Mapping',
        'url' => 'talks/docs/SC_Solenoid_Field_Mapping.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Jefferson Lab Meeting',
    ],
    [
        'date' => '12-2014',
        'title' => 'Status of the Møller Polarimeter',
        'url' => 'talks/docs/Moller_Updates_09Dec2014.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Collaboration Meeting',
    ],
    [
        'date' => '06-2014',
        'title' => 'Charge measurement/Møller Target Controller/HV Control for Hall-A',
        'url' => 'talks/docs/BCM_HV_report.pdf',
        'presenter' => 'Roman Pomatsalyuk',
        'event' => 'Hall-A Weekly Meeting',
    ],
    [
        'date' => '04-2014',
        'title' => 'Hall A Møller Polarimeter Commissioning',
        'url' => 'talks/docs/MollerStatus_HALLA_29Apr2014.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A weekly Meeting',
    ],
    [
        'date' => '04-2014',
        'title' => 'Hall A Møller Polarimeter Status',
        'url' => 'talks/docs/MollerStatus_PREX_11Apr2014.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'PREX/CREX Collaboration Meeting',
    ],
    [
        'date' => '04-2013',
        'title' => 'Status of the Møller Polarimeter',
        'url' => 'talks/docs/HallA_2012_04_23.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Weekly Meeting',
    ],
    [
        'date' => '03-2013',
        'title' => 'Hall A Møller Polarimeter Target Status',
        'url' => 'talks/docs/2013_03_16_RPI.pdf',
        'presenter' => 'Javier Gomez',
        'event' => 'Moller Polarimetry Working Group Meeting',
    ],
    [
        'date' => '12-2012',
        'title' => 'BCM and 12 GeV Möller Polarimeter Commissioning Plan',
        'url' => 'talks/docs/Sasha_Moller_and_BCM.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '11-2012',
        'title' => 'Status of the Hall A Møller Polarimeter',
        'url' => 'talks/docs/sashas_annual_moller_report_2012.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall A annual report (2012)',
    ],
    [
        'date' => '12-2012',
        'title' => 'Hall A Møller Polarimeter 12 GeV Upgrade',
        'url' => 'talks/docs/Jixie_Moller_12GeV_Dec2012.pdf',
        'presenter' => 'Jixie Zhang',
        'event' => 'Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '06-2012',
        'title' => 'Hall A Møller Polarimeter 12 GeV Upgrade',
        'url' => 'talks/docs/Jixie_Moller_12GeV_June2012.pdf',
        'presenter' => 'Jixie Zhang',
        'event' => 'Hall-A Summer Collaboration Meeting',
    ],
    [
        'date' => '04-2012',
        'title' => 'Møller Meeting Notes Apr 20, 2012',
        'url' => 'talks/docs/04202012.pdf',
        'presenter' => 'Roman Pomatsalyuk',
        'event' => 'Moller Polarimetry Working Group Meeting',
    ],
    [
        'date' => '04-2012',
        'title' => '[Part 2] Møller Meeting Notes Apr 20, 2012',
        'url' => 'talks/docs/report_20Apr2012.pdf',
        'presenter' => 'Roman Pomatsalyuk',
        'event' => 'Moller Polarimetry Working Group Meeting',
    ],
    [
        'date' => '12-2011',
        'title' => 'Hall A Møller Polarimeter Update',
        'url' => 'talks/docs/HallA-2011.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '09-2011',
        'title' => 'Møller (Iron Foils) Existing Techniques',
        'url' => 'talks/docs/PAVI11.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'PAVI11, Rome',
    ],
    [
        'date' => '09-2011',
        'title' => 'Møller Polarimetry on Atomic Hydrogen',
        'url' => 'talks/docs/talk_pavi11.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'PAVI11, Rome',
    ],
    [
        'date' => '01-2011',
        'title' => 'Old Møller Target Systematic Error',
        'url' => 'talks/docs/old_target.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'HAPPEX Meeting',
    ],
    [
        'date' => '01-2011',
        'title' => 'Møller Polarimetry for PV',
        'url' => 'talks/docs/Eugene_SoLID.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'SoLID Collaboration Meeting',
    ],
    [
        'date' => '01-2011',
        'title' => 'Møller Polarimeter for PREX',
        'url' => 'talks/docs/PREX_Col_01_29_2011.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'SoLID Collaboration Meeting',
    ],
    [
        'date' => '01-2011',
        'title' => 'Møller FADC DAQ',
        'url' => 'talks/docs/Moller_FADC_DAQ.pdf',
        'presenter' => 'Roman Pomatsalyuk',
        'event' => 'SoLID Collaboration Meeting',
    ],
    [
        'date' => '06-2010',
        'title' => 'Hall A Møller Polarimeter after Upgrade',
        'url' => 'talks/docs/HAColab2010.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Summer Collaboration meeting',
    ],
    [
        'date' => '03-2010',
        'title' => 'Hall A Møller Polarimeter after Upgrade',
        'url' => 'talks/docs/MCC.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'MCC Meeting',
    ],
    [
        'date' => '02-2010',
        'title' => 'Hall A Møller Polarimeter After Upgrade',
        'url' => 'talks/docs/Bteam.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'B-team Meeting',
    ],
    [
        'date' => '02-2010',
        'title' => 'Hall A Møller Polarimeter',
        'url' => 'talks/docs/moller_status_prex.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'PREX Collaboration Meeting',
    ],
    [
        'date' => '12-2009',
        'title' => 'Hall A Møller Polarimeter Upgrade',
        'url' => 'talks/docs/Moller-Upgrade.pdf',
        'presenter' => 'Sasha Glamazdin',
        'event' => 'Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '01-2010',
        'title' => 'Møller Polarimetry for 12 GeV',
        'url' => 'talks/docs/moll_pv-moller_review.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'PV-MOLLER Review',
        'more' => [
            ['text' => 'version with backup slides', 'url' => 'talks/docs/moll_pv-moller_review_full.pdf'],
        ],
    ],
    [
        'date' => '12-2009',
        'title' => 'Møller polarimetry for 12 GeV',
        'url' => 'talks/docs/moll_pv-moller.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'PV-MOLLER \'09',
    ],
    [
        'date' => '06-2009',
        'title' => 'Beam Polarimetry (for Future Experiments at JLab)',
        'url' => 'talks/docs/talk_pavi09.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'PAVI09',
    ],
    [
        'date' => '06-2009',
        'title' => 'Status of the Møller Polarimeter Upgrade',
        'url' => 'talks/docs/Eugene_Moller_11June2009.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'Hall-A Summer Collaboration Meeting',
    ],
    [
        'date' => '08-2008',
        'title' => 'Polarimetry in Hall A',
        'url' => 'talks/docs/polar_halla_12gev.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'MOLLER-12',
    ],
    [
        'date' => '06-2006',
        'title' => 'Møller Polarimeter Upgrade',
        'url' => 'talks/docs/moller_talk_9.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'Hall-A Summer Collaboration Meeting',
    ],
    [
        'date' => '12-2005',
        'title' => 'Møller Polarimeter Status',
        'url' => 'talks/docs/moller_talk_8.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'Hall-A Winter Collaboration Meeting',
    ],
    [
        'date' => '04-2005',
        'title' => 'Electron Beam Polarimetry: Status and Prospects',
        'url' => 'talks/docs/polar_dis2005.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'DIS2005',
    ],
    [
        'date' => '12-2002',
        'title' => 'Stored Polarized Atomic Hydrogen for Møller Polarimetry',
        'url' => 'talks/docs/luppov_dec02.pdf',
        'presenter' => 'V.G. Luppov',
        'event' => 'JLab Meeting',
    ],
    [
        'date' => '11-2002',
        'title' => 'Beam polarimetry at JLab',
        'url' => 'talks/docs/talk_polarimetry_jlab.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'EIC Meeting',
    ],
    [
        'date' => '10-1999',
        'title' => 'Møller Polarimetery for HAPPEX',
        'url' => 'talks/docs/talk_2.pdf',
        'presenter' => 'Eugene Chudakov',
        'event' => 'HAPPEX (15 October 1999)',
    ],

]);


PageEnd();
